name: Docker Compose Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose-plugin

      - name: Build and run Docker Compose
        run: |
          docker-compose -f docker-compose.yml up --build -d

      - name: Check running containers
        run: |
          docker ps --filter "name=my_service" --format "{{.Status}}" | grep -q "Up"

      - name: Check container logs
        run: |
          docker-compose logs my_service | grep -q "Application started"

      - name: Stop and remove containers
        run: |
          docker-compose -f docker-compose.yml down