version: '3.8'

services:
  bot:
    build: .
    container_name: discord-bot-V2.0
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - BIRTHDAY_ROLE_ID=${BIRTHDAY_ROLE_ID}
      - COLLOQUIUM_ID=${COLLOQUIUM_ID}
      - USERS_TO_MENTION=${USERS_TO_MENTION}
      - DATABASE_FILE=${DATABASE_FILE}
      - TZ=Europe/Minsk
    volumes:
      - ./data:/app/data  # Сохраняем данные SQLite на хосте
    restart: unless-stopped
    