name: Docker Compose Test

on:
  push:
    branches:
      - main  # Запускать при пуше в ветку main
  pull_request:
    branches:
      - main  # Запускать при создании пул-реквеста в ветку main

jobs:
  test-docker-compose:
    runs-on: ubuntu-latest  # Используем последнюю версию Ubuntu

    steps:
      # Шаг 1: Получить код из репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Установить Docker
      - name: Set up Docker
        uses: docker/setup-qemu-action@v2  # Устанавливаем Docker

      # Шаг 3: Установить Docker Compose вручную
      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Проверяем установку 

      # Шаг 5: Запустить сборку и запуск контейнеров через docker-compose
      - name: Build and run Docker Compose
        run: |
          docker-compose -f docker-compose.yml up --build -d
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}  # Используем секрет из GitHub Secrets

      # Шаг 6: Проверить, что контейнеры запущены
      - name: Check running containers
        run: |
          docker ps --filter "name=discord-bot-V2.0" --format "{{.Status}}" | grep -q "Up"

      # Шаг 7: Проверить логи контейнера (опционально)
      - name: Check container logs
        run: |
          docker-compose logs discord-bot-V2.0 | grep -q "Application started"

      # Шаг 8: Остановить и удалить контейнеры
      - name: Stop and remove containers
        run: |
          docker-compose -f docker-compose.yml down